oe-lite/base

recipes/fastcgi/fastcgi.inc
=> fastcgi: Fix build by providing C++ compiler

recipes/procstat/procstat.oe, recipes/procstat/procstat.oe.sig
=> procstat: New recipe

recipes/u-boot/u-boot-tools.inc
=> u-boot-tools: Support FIT image creation

recipes/busybox/busybox-configure.inc
=> busybox: Add USE flag to enable '-o loop' support in mount command

recipes/rsync/rsync_3.1.1.oe
Hoping that this resolves rebuild issue.
=> rsync: Do VPATH build

recipes/libmodbus/libmodbus_3.1.2.oe, recipes/libmodbus/libmodbus_3.1.2.oe.sig
=> libmodbus: Add version 3.1.2 (latest unstable)

recipes/openssh/files/init
=> openssh: Generate ECDSA host key

recipes/libiconv/libiconv.inc
=> libiconv: Add package dependencies

recipes/busybox/busybox-configure.inc
Signed-off-by: Klaus Henning Sorensen <klaus.sorensen@prevas.dk>
=> Add busybox use flags to include chroot command

recipes/busybox/busybox-configure.inc
Signed-off-by: Klaus Henning Sorensen <klaus.sorensen@prevas.dk>
=> Add use flag to set boot message verbosity level

recipes/mtd/mtd-utils_1.5.1.oe, recipes/mtd/mtd-utils_1.5.2.oe, recipes/mtd/mtd-utils_1.5.2.oe.sig
Updated mtd-utils 1.5.2 that compiles with gcc5.2
=> Updated mtd-utils

recipes/liblogging/liblogging_1.0.5.oe, recipes/liblogging/liblogging_1.0.5.oe.sig
=> Liblogging

recipes/busybox/busybox-configure.inc
Cherry-pick of busybox change from PR #167.
=> busybox: add readlink -f (follow) to readlink use flag

recipes/rsyslog/rsyslog.inc, recipes/rsyslog/rsyslog_8.1.3.oe, recipes/rsyslog/rsyslog_8.1.3.oe.sig, recipes/rsyslog/rsyslog_8.6.0.oe, recipes/rsyslog/rsyslog_8.6.0.oe.sig
=> Rebase of rsyslog PR

recipes/gdb/gdb.inc
=> gdb: Fixup rdepends, so that "gdb" actually pulls in gdb

recipes/valgrind/valgrind-3.10.1/0001-Add-glibc-2.22-support.patch, recipes/valgrind/valgrind_3.10.1.oe
=> valgrind: added glibc 2.22 support

recipes/busybox/busybox-initramfs.inc, recipes/busybox/busybox.inc
Will ease making customized BSP's
=> busybox: udhcpcd.conf in separate package, udhcpd-config

recipes/libressl/libressl.inc, recipes/libressl/libressl_2.2.4.oe, recipes/libressl/libressl_2.2.4.oe.sig
=> libressl: Added version 2.2.4

recipes/busybox/busybox-configure.inc
=> busybox: Add use flags and fix less_regexp flag

recipes/libgpg-error/libgpg-error.inc
=> libgpg-error: Added support for Aarch64 arch

recipes/expat/expat-2.1.0/expat-CVE-2015-1283.patch, recipes/expat/expat_2.1.0.oe
=> expat: Added CVE patch

recipes/libusb/libusb1.inc, recipes/usbutils/usbutils_007.oe
libusb1 and usbutils fixes, for building imx-usb-loader (meta/fsl) for sdk
=> imx-usb-loader

recipes/zip/unzip.inc, recipes/zip/unzip/06-unzip60-alt-iconv-utf8_CVE-2015-1315.patch, recipes/zip/unzip/09-cve-2014-8139-crc-overflow.patch, recipes/zip/unzip/10-cve-2014-8140-test-compr-eb.patch, recipes/zip/unzip/11-cve-2014-8141-getzip64data.patch, recipes/zip/unzip/CVE-2015-7696.patch, recipes/zip/unzip/CVE-2015-7697.patch, recipes/zip/unzip/avoid-strip.patch, recipes/zip/unzip/cve-2014-9636.patch, recipes/zip/unzip/define-ldflags.patch, recipes/zip/unzip_6.0.oe, recipes/zip/unzip_6.0.oe.sig
Based on unzip.bb from openembedded-core + packaging + do_configure
=> unzip: Added

recipes/ntp/files/ntpd, recipes/ntp/ntp.inc
I needed my ntpd to be started with -g -x.
Found this to be the best solution
=> ntp: Added useflag for ntpd options

recipes/makedevs/makedevs-1.0.0/makedevs.c
=> makedevs: Fix handling of paths longer than 40 (max is now 4095)

recipes/openssh/files/init
=> openssh: Fix generation of non-rsa host keys

recipes/busybox/busybox-configure.inc, recipes/busybox/files/busybox-ifplugd.conf
With this update it becomes possible to pre-config ifplugd to e.g. support two networks
=> busybox: Added USE flags for customization of ifplugd.conf

recipes/openssh/openssh.inc
=> openssh: Allow USE flag override of HOST_KEY_TYPES

recipes/busybox/busybox-configure.inc
=> busybox: Add USE flag to enable nameif command

recipes/mpdecimal/mpdecimal-2.4.2/fix-mingw-lib-names.patch, recipes/mpdecimal/mpdecimal.inc, recipes/mpdecimal/mpdecimal_2.4.2.oe, recipes/mpdecimal/mpdecimal_2.4.2.oe.sig
=> mpdecimal: new recipe

recipes/bluez/bluez-5.35/0001-hciattach-add-fixed-delay-between-brf-actions-for-te.patch, recipes/bluez/bluez_5.35.oe
This fixed initialization of texas devices with hciattach. See patch for
detailed description.
=> bluez: add patch to fix initialization of texas devices.

recipes/parted/files/compile-failure-while-dis.patch, recipes/parted/parted.inc, recipes/parted/parted_3.2.oe, recipes/parted/parted_3.2.oe.sig
=> parted: added recipe for version 3.2

recipes/watchdog/files/fix-ping-failure.patch, recipes/watchdog/files/fixsepbuild.patch, recipes/watchdog/files/watchdog.init, recipes/watchdog/watchdog.inc, recipes/watchdog/watchdog_5.14.oe, recipes/watchdog/watchdog_5.14.oe.sig
Recipe and patches is derived from openembedded
=> watchdog: Added watchdog deamon version 5.14

recipes/libusb/libusb1.inc
=> libusb: Allow building for non-Linux archs

recipes/screen/screen-4.2.1/0001-compiler-sanity-checks.patch, recipes/screen/screen-4.2.1/0002-no-memcpy-fallback.patch, recipes/screen/screen-4.2.1/0003-cross-compilation-AC_TRY_RUN.patch, recipes/screen/screen-4.2.1/0004-cross-compilation-ignore-host-fs.patch, recipes/screen/screen-4.2.1/0005-avoid-identifying-as-SVR4.patch, recipes/screen/screen-4.2.1/0006-install-no-backup-binary.patch, recipes/screen/screen-4.2.1/0007-install-always-chmod.patch, recipes/screen/screen-4.2.1/0008-install-nonversioned-binary.patch, recipes/screen/screen-4.2.1/0009-install-dir-dependency.patch, recipes/screen/screen-4.2.1/0010-rename-sched_h.patch, recipes/screen/screen.inc, recipes/screen/screen_4.2.1.oe, recipes/screen/screen_4.2.1.oe.sig
=> screen: First commit of screen 4.2.1

recipes/canfestival/canfestival.oe, recipes/canfestival/canfestival.oe.sig, recipes/canfestival/files/0001-install-pkgconfig-module-for-canfestival.patch, recipes/canfestival/files/0002-allow-to-set-python-interpreter.patch
canfestival implements the CANOpen protocol
=> canfestival: new recipe

recipes/libqmi/libqmi_1.16.0.oe, recipes/libqmi/libqmi_1.16.0.oe.sig
=> libqmi: add initial version 1.16

recipes/boost/boost.inc, recipes/boost/boost_1.57.0.oe, recipes/boost/boost_1.57.0.oe.sig, recipes/boost/boost_1.59.0.oe, recipes/boost/boost_1.59.0.oe.sig, recipes/boost/files/0001-Do-not-qualify-fenv.h-names-that-might-be-macros.patch
also add a boost-full package to make it easy to pull
in everything.
=> update boost to more recent version

recipes/avahi/avahi.inc
The second patch relies on a pending PR in meta/core, so I don't expect the build test to pass.
=> minor avahi fixes

recipes/libcap/libcap2.inc
=> libcap2: added native to recipe types

recipes/glib/glib-common.inc
=> glib: dump locale files in locale package

recipes/coreutils/coreutils-8.25/amversion.patch, recipes/coreutils/coreutils-8.25/man-decouple-manpages-from-build.patch, recipes/coreutils/coreutils-8.25/remove-usr-local-lib-from-m4.patch, recipes/coreutils/coreutils.inc, recipes/coreutils/coreutils_8.25.oe, recipes/coreutils/coreutils_8.25.oe.sig
This is a small step towards a busybox free embedded system
=> coreutils: add version 8.25

recipes/attr/attr.inc, recipes/attr/files/0002-avoid-glibc-specific-decls-defines.patch, recipes/attr/files/0003-portability-fixes.patch
=> attr: added portability fixes (uclibc and musl)

recipes/ppp/files/0001-Fix-build-with-musl.patch, recipes/ppp/ppp.inc
=> ppp: fix musl build

recipes/libwebsockets/libwebsockets_2.0.2.oe, recipes/libwebsockets/libwebsockets_2.0.2.oe.sig, recipes/libwebsockets/libwebsockets_2.1.0.oe, recipes/libwebsockets/libwebsockets_2.1.0.oe.sig
Update libwebsockets to latest stable release
=> Jsch/libwebsockets 2.1

recipes/libusb/libusb1_1.0.20.oe
=> libusb: fixed race in do_compile

recipes/gdb/files/0001-include-sys-types.h-for-mode_t.patch, recipes/gdb/files/0002-make-man-install-relative-to-DESTDIR.patch, recipes/gdb/files/0004-ppc-ptrace-Define-pt_regs-uapi_pt_regs-on-GLIBC-syst.patch, recipes/gdb/files/0008-Use-exorted-definitions-of-SIGRTMIN.patch, recipes/gdb/files/0009-Change-order-of-CFLAGS.patch, recipes/gdb/files/0010-resolve-restrict-keyword-conflict.patch, recipes/gdb/files/0011-avx_mpx.patch, recipes/gdb/gdb_7.10.1.oe, recipes/gdb/gdb_7.10.1.oe.sig, recipes/gdb/gdb_7.11.oe, recipes/gdb/gdb_7.11.oe.sig
I know it's one version old, but i think we should wait for some yocto patches before upgrading
=> gdb: add version 7.11

recipes/connman/connman-1.33/0002-resolve-musl-does-not-implement-res_ninit.patch, recipes/connman/connman-1.33/connman, recipes/connman/connman-1.33/includes.patch, recipes/connman/connman.inc, recipes/connman/connman_1.33.oe, recipes/connman/connman_1.33.oe.sig
Signed-off-by: Sean Nyekjaer sean@nyekjaer.dk
=> connman: add version 1.33 (new recipe)

recipes/nano/nano.inc, recipes/util-linux/util-linux.inc, recipes/vim/vim.inc
As part of some code cleanup in meta/core, I'd like to eliminate uses of the bb.data module. There shouldn't be a gazillion different ways of getting the value of a variable.
=> replace bb.data.getVar

recipes/berkeley-db/db6.inc, recipes/coreutils/coreutils.inc, recipes/cryptsetup/cryptsetup_1.6.2.oe, recipes/initscript/initramfs-init.inc, recipes/lua/lua.inc, recipes/lua/lua_5.2.1.oe, recipes/mysql/mysqludf-sys.oe, recipes/nspr/nspr_4.10.oe, recipes/ofono/ofono.inc
I noticed I made a typo in the ofono recipe, then did a little fuzzy greping to see what else we could easily fix.
=> speling fixez

recipes/busybox/busybox-1.25.1/mdev-create-devices-from-sys-dev.patch, recipes/busybox/busybox_1.25.1.oe
=> busybox: add patch mdev: create devices from /sys/dev

recipes/dhcpcd/dhcpcd.inc, recipes/dhcpcd/dhcpcd_6.11.5.oe, recipes/dhcpcd/dhcpcd_6.11.5.oe.sig, recipes/dhcpcd/files/init
Lightly tested on a wandboard (where busybox' ifup automatically invokes it).
=> add dhcpcd recipe

recipes/bzip2/bzip2.inc
Using AUTO_PACKAGE_UTILS_SYMLINKS_* automatically does these FILES_* and
PROVIDES_* settings.
=> bzip2: use AUTO_PACKAGE_UTILS_SYMLINKS

recipes/chrony/chrony.inc, recipes/chrony/chrony_3.1.oe, recipes/chrony/chrony_3.1.oe.sig, recipes/chrony/files/chrony.conf, recipes/chrony/files/init
I haven't had the opportunity to test this on any target yet, but at least it build pretty cleanly.
=> add chrony recipe

recipes/misc/wtmptrim.oe, recipes/misc/wtmptrim/wtmptrim.c, recipes/s6-init/s6-init.oe, recipes/s6-init/s6-init/init-utmp.up
Add a wtmptrim util, use it in s6-init's init-utmp, and create /var/log/btmp with appropriate permissions.
=> some wtmp handling

recipes/mmc-utils/mmc-utils.oe
=> mmc-utils: New recipe

recipes/bswap/bswap-cli.oe
=> bswap-cli: New recipe

recipes/busybox/busybox.inc, recipes/busybox/files/busybox-mdev, recipes/busybox/files/rcS, recipes/fontconfig/fontconfig.inc
The third patch is taken from a downstream BSP and should make sense for master. The other three are some (back- and forward compatible, I believe) patches that should ease transitioning from said BSP to a newer linux kernel and upstream meta/base. The busybox patch is how I believe it always should have been.
=> some compat patches

recipes/glib/glib_2.50.1.oe
=> glib: Fix mingw bug
