oe-lite/base

recipes/dtc/dtc.inc
=> dtc: Fix git url to use git.kernel.org

recipes/dupdate/dupdate_2.0.0.oe
Make the directory to watch for new firmware configurable
via a use flag.
This is necessary for targets where the dupdate archive
is larger than the space available in /tmp.
Signed-off-by: Klaus Henning Sorensen <klaus.sorensen@prevas.dk>
=> Add use flag to set directory to watch for new firmware

recipes/busybox/files/busybox-watchdog
In my experience, the busybox watchdog app creates and deletes
the /var/run/watchdog.pid file, and the explicit creation/deletion
of the pidfile in the busybox-watchdog script leads to warning
messages when stopping busybox-watchdog.
=> Remove explicit handling of PIDFILE for watchdog app

recipes/rsyslog/rsyslog.inc
This has been verified to solve the problem just seen with rebuild failure
after do_stage being rerun.
=> rsyslog: Fix rebuild bug by using make vpath

recipes/openssh/files/init, recipes/openssh/openssh.inc
Avoid copy-paste of that 4 line conditional block, and update with current
list of 4 host key types.
=> openssh: Make ssh key generation more flexible and extend with ed25519

recipes/libtiff/tiff.inc
currently there is a rebuild issue for mingw, issue tracked in
oe-lite/base issue #220
=> libtiff: disable build for mingw

recipes/makedevs/makedevs-1.0.0/makedevs.c
The mode setting for directories in device table files were ignored in
add_new_directory(). Fix this by adding a call in chmod() in said
function.
=> makedevs: apply mode setting on directories

recipes/rsyslog/rsyslog/rsyslog
=> rsyslog: The "-c5" option is not compatible with rsyslog 8.6.0

recipes/busybox/busybox-install.inc
Make sure /etc is created, even if no other /etc using USE flags are
enabled.
=> busybox: Fix busybox_mdev USE flag handling

recipes/net-snmp/net-snmp.inc, recipes/net-snmp/net-snmp_5.4.5.pre1.oe, recipes/net-snmp/net-snmp_5.4.5.pre1.oe.sig, recipes/net-snmp/net-snmp_5.7.3.oe
According to http://www.net-snmp.org/dev/schedule.html the net-snmp 5.4.x is a long term stable branch. Still maintained. Adding the pre1 release instead of the 5.4.4 release as many/all patches from that branch seems usefull/needed.
Upstream git branch for 5.4.x (V5-4-patches) is found here: http://sourceforge.net/p/net-snmp/code/ci/V5-4-patches/tree/
=> Net snmp old stable

recipes/u-boot/u-boot-tools.inc
Re-apply the addition of FIT image support.  It was added in PR #43 and
silently dropped in PR #244.
(cherry picked from commit 00e1ff920644bec4ffe2222c5cd045ccc7212370)
=> u-boot-tools: Support FIT image creation

recipes/kexec-tools/kexec-tools-2.0.10/autotools.patch
=> kexec-tools: distclean no longer removes config.h.in

recipes/curl/curl.inc
When inheriting library, one must be carefull to not overwrite DEPENDS,
as library.oeclass sets up the library dependency for ${PN}-dev.
Fix this in the curl recipe by appending to DEPENDS instead of assigning
to it.
=> curl: fix libcurl-dev DEPENDS for libcurl

recipes/dropbear/dropbear.inc
When using non-root users on the target, one might want to disable root
logins in dropbear/ssh, so make this possible with a use flag:
USE_dropbear_no_root_login
=> dropbear: add useflag to disable root login

recipes/openssh/files/passwd
The directory /home/sshd presumably doesn't exist, so set it to
/var/run/sshd which is in any case the working directory for sshd
(it's created by the init script). Also, it doesn't make sense to log
in as sshd, so change its shell to /bin/false.
=> openssh: change home dir and shell for sshd user

recipes/busybox/busybox-configure.inc
In d552158 and fd1f2c3, a new specification of this flag was added,
while the the old one was left in recipe.  The old specification is
processed last, and the result has been that the flag has been enabled
by default (as specified in the new specification), while
CONFIG_FEATURE_MOUNT_LOOP_CREATE was not enabled.
This change removed the old specification, and the visible change is
that CONFIG_FEATURE_MOUNT_LOOP_CREATE is now (also) enabled by the flag.
=> busybox: Fixup USE_busybox_feature_mount_loop

recipes/openssl/openssl.inc
Despite the buildbot apparently succeeding in building
920f96645787f9360dcf94131be885fedb6fac00, parallel building of openssl
is still broken.
Two of the five machine builds at
http://buildbot.oe-lite.org/builders/core/builds/263 failed at the
do_install part of the openssl recipe, and when trying to reproduce
locally, I found that it fails the same way using current master of
both base and core (9a22db1fcf4afe3f783929037ecb388944ce289f and
3fae0aed44ef844caee6f361fc564f2d0428cbf7, respectively).
Since parallel do_compile appararently works fine, this is an attempt
to hooking into just do_install and disabling it there. It does rely
on make grokking -j, but any make implementation not supporting that
should be shot and moved to /dev/null.
=> openssl: disable parallel build for do_install

recipes/libxml/libxml2.inc
previously the build relied on the buildhost installed python, but
this causes problems when dealing with python paths. Switch to use
the oe-lite python now that we have it.
Hopefully we can make some python oeclass later to deal with most of
what is being done here.
=> libxml2: use oe-lite python for python support

recipes/u-boot/u-boot-tools-2015.10/0001-tools-env-include-compiler.h.patch, recipes/u-boot/u-boot-tools_2015.10.oe
Backport a fix from upstream u-boot to fix compilation on recent
compilers.
Without this, the following error occurs (among others):
HOSTCC  tools/env/ctype.o
tools/env/fw_env.c:54:2: error: unknown type name 'uint8_t'
uint8_t mtd_type;  /* type of the MTD device */
^
=> u-boot-tools: add patch to fix compilation on recent compilers

recipes/pkg-config/pkg-config.inc
The official pkg-config mirror has moved to https://, and emits an HTTP
301 when connecting to http://, which urlgrabber fails to follow.
Fix this by using https:// explicitly in the SRC_URI
=> pkg-config: update src uri

recipes/glib/glib-2.44.0/001-fix-error-wont-overwrite-defined-macro.patch, recipes/glib/glib_2.44.0.oe
Without this patch, autoreconf refuses to overwrite AC_DEFUN and
AC_REQUIRE.
autoreconf is needed to fix glibs calling of version specific automakes
during build (automake-1.14), when other versions are installed on the
system (e.g. automake-1.15 on ubuntu-16.04).
=> glib: fix autoreconf on recent autotools

recipes/libunwind/libunwind.inc, recipes/libunwind/libunwind_1.2-rc1.oe, recipes/libunwind/libunwind_1.2-rc1.oe.sig
The reason for adding a this rc1, is develepment is stalled a long time ago
before aarch64 supprt etc...
=> libunwind: added version 1.2-rc1

recipes/busybox/busybox.inc, recipes/busybox/files/speed_table.patch
Probably due to memory usage the baudrate is coded to make it possible to
store it in a short.
This is done by dividing high baudrates by 256 (shift 8 bits) and raising
MSB to signal the division.
This way baudrates being dividable with 256 and not greater than 8388352
can be stored.
To make support for the 'odd' baudrates of 1500000, 2500000 etc bit 14
(MSB -1) has bin chosen to signal a divisor of 250.
Drawback is that coded max, after being divided by 256, must now not
exceed 0x3FFF causing maximum baudrate to be 4194048
or 4095750 for baudrates dividable by 250
=> busybox: stty: Allow baudrates up to 4000000

recipes/libunwind/libunwind.inc, recipes/libunwind/libunwind_1.2-rc1.oe
Utilizing the new AUTO_PACKAGE_LIBS_LIBPREFIX, along with the existing
PROVIDEPREFIX and PKGPREFIX, we can arrange that the recipe generates
packages "libunwind-setjmp", "libunwind-coredump", etc. which provide
the .so files of the same name.
While at it, make sure this is only compatible with arm for now. The
proper fix would be to extract the proper arch string and use that
instead of the hardcoded "arm".
Another nice-to-have is a use-flag for enabling lzma.
For now, let's just be content with the fact the packageqa passes,
whatever that means.
Signed-off-by: Rasmus Villemoes <rasmus.villemoes@prevas.dk>
=> libunwind: make it a little neater

recipes/dmalloc/dmalloc_5.5.2.oe
We sometimes see dmalloc failing to build due to a mysterious
duplicate cross compile prefix
(e.g. arm-926ejs-linux-gnueabi-arm-926ejs-linux-gnueabi-ld). This
string can appear in the Makefile if do_compile is run twice, since
the fix_ld hack is not idempotent.
I haven't found a way to reliably reproduce the actual problem, but
the wrong makefile is easy to reproduce:
oe bake dmalloc -y
rm tmp/stamp/machine/arm-926ejs-linux-gnueabi/dmalloc-5.5.2/do_compile
oe bake dmalloc -y
less tmp/work/machine/arm-926ejs-linux-gnueabi/dmalloc-5.5.2/src/dmalloc-5.5.2/Makefile
But unfortunately, in this case, the second bake fails to fail, since
the rules containing those ld calls don't get used by make (everything
was already succesfully built). However, the buildbot definitely
experiences this from …
=> dmalloc: make fix_ld hack more robust

recipes/barebox/barebox.inc, recipes/barebox/barebox_2012.02.0.oe, recipes/barebox/barebox_2012.02.0.oe.sig
The current barebox recipe is a little flaky (the .inc file points to
a version-specific SRC_URI, and the .oe file overrides that with a
SRC_URI pointing to a commit which is not v2012.02, but actually just
two commits shy of v2012.03). It also causes problems for at least one
downstream user of oe-lite (preventing "oe bake world" from even
parsing) because of the default dependency on the existence of a
barebox-defconfig recipe. Nuke it.
=> barebox: remove recipe

recipes/dmalloc/dmalloc_5.5.2.oe
Observer with make -j8:
"
+ do_compile_make
+ '[' -e Makefile -o -e makefile ']'
+ oe_runmake
+ make -j8 cxx cxxsl threads threadssl threadscxx threadscxxsl utils shlib
rm -f dmalloc.h dmalloc.h.t
...
aarch64-cortexa53t-linux-gnu-gcc -O2 -fexpensive-optimizations \
-fomit-frame-pointer -frename-registers  -fPIC   -DHAVE_STDARG_H=1 \
-DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_MMAN_H=1 \
-DHAVE_SYS_TYPES_H=1 -DHAVE_W32API_WINBASE_H=0 -DHAVE_W32API_WINDEF_H=0 \
-DHAVE_SYS_CYGWIN_H=0 -DHAVE_SIGNAL_H=1  -I. \
-I/build/tmp/work/machine/aarch64-cortexa53t-linux-gnu/dmalloc-5.5.2/src/dmalloc-5.5.2 \
-c dmalloc_argv.c -o ./dmalloc_argv.o
/build/tmp/work/machine/aarch64-cortexa53t-linux-gnu/dmalloc-5.5.2/src/dmalloc-5.5.2/dmallocc.cc:41:21: \
fatal error: dmalloc.h: No such …
=> dmalloc: disable parallel make

recipes/vsftpd/vsftpd.inc
A change in passwd.oeclass means the copy of our passwd file is no
longer where this function expects it to be. Rather than just fixing
the path (which shouldn't contain a hard-coded passwd.d anyway), do
what mysql does and patch it in the SRCDIR before passwd.oeclass gets
its hands on it.
=> vsftpd: fix set_ftp_home postfunc

recipes/bind/bind.inc
The RDEPENDS variable makes no sense without a trailing packagename (and
it screws up 'oe bake bind -t do_fetchall'. Fix it by adding the correct
'_${PN}'.
=> bind: fix wrong RDEPENDS variable

recipes/mysql/mysql-tools_5.6.13.oe, recipes/mysql/mysql_5.6.13.oe, recipes/mysql/mysqludf-sys.oe
GCC 6 series breaks this build.
If someone needs this functionality, they could add fx mariaDB
=> mysql: added compatible flag "gcc-older-than-6.x"

recipes/gnupg/gnupg.inc
One would think that
RDEPENDS_gnupg = "gpgv" # in gnupg.inc
RDEPENDS_${PN} += "libc" # later, in gnupg_2.0.29.oe
would end up giving RDEPENDS_gnupg the value "gpgv libc". However:
$ oe show gnupg | grep ^RDEPENDS_gnupg=
RDEPENDS_gnupg='libc'
This is a consequence of how core_varname_expansion works and the fact
that for simple variable assignments, the varname is not expanded
immediately.
=> gnupg: fix RDEPENDS setting

recipes/can-utils/can-utils.oe
The upstream Makefile has PREFIX hard-coded to /usr/local
=> can-utils: Fix installation prefix

recipes/opencv/opencv.inc, recipes/opencv/opencv/0001-cmake-fix-for-GCC-6.x.patch
=> opencv: fix build for gcc 6.x

recipes/base-files/base-files.oe
=> base-files: exclude libnss for musl build

recipes/openssl/openssl.inc
=> openssl: termio.h is not linux specific but it's libc specific

recipes/util-linux/util-linux.inc
All our current libc's depends on the same packages,
so remove this condition
=> util-linux: move specific glibc and uclibc depends to depends

recipes/fuse/fuse.inc
Without this fix, you will end up creating ${D}/dev/fuse when building
with mknod privileges. And as /dev/fuse is not included in any package,
do_split barfs.
Yes, you probably shouldn't do this.  But if (when) done, there is no
good reason to fail in this odd way.
=> fuse: Fix build when running with mknod privileges

recipes/libnl/libnl_3.2.28.oe
This fixes builds where the m4 directory already exits
=> libnl: create m4 directory unconditionally

recipes/libxml/libxml2.inc
There are two reasons the python_setup function does nothing: It is
never run because of the prefuncS typo. And even if it did get run, it
would be in a different shell instance than where the do_configure
function runs.
Try to fix this by just defining the variables and setting proper
flags ensuring they're only emitted to the do_configure task.
=> libxml2: actually (try to) use oe-lite python

recipes/busybox/files/groups
Running "groups sshd" as root reveals the groups of the... root user!
Append the given arguments to the id invocation.
=> busybox: fix groups emulation script

conf/distro/base.conf, recipes/bind/bind.inc, recipes/busybox/busybox-configure.inc, recipes/busybox/busybox-initramfs.inc, recipes/busybox/busybox.inc, recipes/cryptsetup/cryptsetup_1.6.2.oe, recipes/dhcp/dhcp4.inc, recipes/dropbear/dropbear.inc, recipes/gdb/gdb.inc, recipes/glib/glib.inc, recipes/hiawatha/hiawatha.inc, recipes/libgcrypt/libgcrypt.inc, recipes/libtiff/tiff.inc, recipes/lighttpd/lighttpd.inc, recipes/mosquitto/mosquitto.inc, recipes/net-snmp/net-snmp.inc, recipes/netperf/netperf.inc, recipes/ntp/ntp.inc, recipes/rsyslog/rsyslog_8.6.0.oe, recipes/splashutils/splashutils.inc, recipes/sqlite/sqlite3.inc, recipes/wpa-supplicant/wpa-supplicant.inc
The OE-lite lexer recognizes True and False as tokens, and currently ends up storing the strings "1" and "0", respectively. This means that these patches are all semantic noops (they also do not change metadata hashes). However, they serve to highlight which USE flags are actually meant as boolean on/off switches, as opposed to those whose string value is used.
=> Saner boolean use flag initializers

recipes/bind/bind.inc
Without this, I see:
checking for json library... no
checking for zlib library... yes
checking for library containing deflate... no
configure: error: found zlib include but not library.
Error: Command failed: 'LC_ALL=C ..../bind-9.11.0-P1/tmp/do_configure.20161111151724.run': 1
=> bind: USE flag control of libz dependency

recipes/busybox/busybox-configure.inc
The [precondition] flag was introduced in meta/core commit b275b0c33a8,
but has never worked the way it was supposed to - instead, any variable
with this flag gets unconditionally deleted(!). So regardless of the
value of USE_busybox_syslogd_remote, the function
do_configure_busybox_syslogd_remote would not exist, in which case
OE-lite happily substitutes a succesful no-op function.
Moreover, the right-hand side of this [precondition] assignment is wrong
- we already append the prefunc conditional on
USE_busybox_syslogd_remote, so this was supposed to further check that
USE_busybox_syslogd_remote_host was set to a non-empty string.
Effectively, no-one has ever been able to use the busybox_syslogd_remote
feature by setting USE_busybox_syslogd_remote. But the [precondition]
line has served …
=> busybox-configure.inc: remove use of broken [precondition] flag

recipes/monit/monit.inc, recipes/monit/monit_5.20.0.oe
Apparently, bitbucket imposes some rather harsh download rate
limits (5000 downloads per hour). The buildbot occasionally hits that,
causing entirely unrelated builds to fail, so let's avoid bitbucket URLs
when we can. In this case the monit website itself also hosts the
tar-balls.
While at it, move the SRC_URI definition to the .inc files as it's
normally done.
=> monit: change away from bitbucket URL

recipes/monit/files/fix-rebuild.patch, recipes/monit/monit.inc
I can consistently reproduce the error we see on the
buildbot (Makefile.in missing) by first
successfully building monit from a clean slate, then removing
tmp/stamp/machine/arm-926ejs-linux-gnueabi/monit-5.20.0/do_configure and
trying to build it again. Adding the fix-rebuild.patch makes that
problem go away.
I then tried to stress it a little by removing random stamp files, and
it didn't take long for do_compile to fail; most often with a "undefined
reference to yyerror", but also with something like
mv: cannot stat 'src/.y.tab.c': No such file or directory
These, and the inconsistent occurrence, strongly indicate a parallel
make problem, and sure enough, upstream actually says "Do not run make
in parallel"
<https://bitbucket.org/tildeslash/monit/issues/238/make-failed>.
Disabling …
=> monit: re-add fix-rebuild.patch and disable parallel make

recipes/boost/boost.inc
First of all, the addhook statement has the side-effect of setting the
emit flag to "" for the function in question, so add_deps is not
available when do_fetch runs, so this does nothing. (When asked to run a
non-existing function, OE-lite substitutes an always-successful noop
function.) I also fail to see what setting an RDEPENDS_ variable has to
do with do_fetch.
=> boost.inc: remove stray do_fetch prefunc

recipes/cppunit/cppunit.inc
The --enable-{doxygen,dot} configure options default to 'auto', which
at least on my build host causes them to be picked up, which then
causes do_split to fail due to lots of files in
/usr/share/cppunit.
=> cppunit: explicitly disable doxygen and dot

recipes/opencv/opencv.inc
libdl is only listed as a package dependency for the package opencv, not
as a build dependency. Doing "oe bake opencv" works fine, but trying to
build anything that DEPENDS on opencv gives
FATAL: No provider for machine:libdl (needed by machine:opencv)
in the mingw build. Move the libdl dependency to the DEPENDS_LIBC
variable which is cleared for the mingw build. While maybe not the
correct/best fix, both native:opencv and machine:opencv pass packageqa
for both mingw and arm-926ejs.
=> opencv: fix mingw build

recipes/libwebsockets/libwebsockets.inc, recipes/libwebsockets/libwebsockets_2.1.0.oe.sig
Lots of buildbot builds are failing since the libwebsockets git
repository is no longer accessible via this URL. Use github instead.
=> libwebsockets: update SRC_URI

recipes/busybox/busybox-configure.inc
This keeps the current default algorithm at DES, but allows configuration
via USE_busybox_feature_default_passwd_algo to other valid values such as
md5, sha256 and sha512.
=> busybox: Allow configuration of default passwd algorithm

recipes/oprofile/oprofile.inc, recipes/oprofile/oprofile/tidy-powerpc64-bfd-target-check.patch, recipes/oprofile/oprofile_0.9.9.oe, recipes/oprofile/oprofile_0.9.9.oe.sig, recipes/oprofile/oprofile_1.1.0.oe
When trying to build the upgraded oprofile recipe for a wandboard, I hit an annoying problem in do_configure which I haven't been able to solve properly. This reinstates the old version and patches things up so they can coexist until someone figures out to make 1.1.0 actually build (unfortunately, buildbot doesn't build oprofile).
=> oprofile fixes

recipes/util-linux/util-linux.inc
When trying to compile with USE_ncurses set, I hit lots of weird
errors. I think part of the problem is that --with-ncursesw is 'auto' by
default, so it is not enough to disable that in the !USE_ncurses case,
it very much also has to be explicitly disabled when we want to use the
--with-ncurses option. Otherwise, the configure script tries
to run ncursesw-config, which it happened to pick up from the host, and
then it obviously fails when it can't link with libncursesw.
But we also have to explicitly disable widechar support to convince the
configure script that --with-ncurses is ok, otherwise one gets a
non-helpful
wide-char support enabled, but non-wide ncurses selects
For me (with MACHINE_CPU = "arm-926ejs"), the end result passes
packageqa with and without USE_ncurses set.
=> util-linux: ncurses fixups

recipes/busybox/busybox.inc, recipes/busybox/busybox_1.25.1.oe, recipes/busybox/files/rtc.down, recipes/busybox/files/rtc.up
This adds an s6-rc service called rtc, which reads hardware clock (RTC)
on start, and writes it on stop.  It can be handy as startup and shutdown
service.
If /etc/hwclock/UTC file exists and does contain something else than the
string "1", the time hwclock is assumed to contain local time. Otherwise,
it is assumed to contain UTC time.
If /etc/hwclock/DEVICE file exists, it specifies the RTC device to use.
Otherwise, /dev/rtc is used.
=> busybox: Add s6-rc integration of hwclock

recipes/netbase/netbase/net-udhcpc.hook
This fixes a bug causing an empty `udhcpc@` service to be created when
dhcp-interfaces returns no interfaces.
=> netbase: Fix creation of dummy udhcpc@ service

recipes/lighttpd/lighttpd.inc
All direct references to the /www directory is specified by the lighttpd.conf
file, so when using a custom lighttpd-config, it is very likely that you would
not want to have the /www included.
=> lighttpd: Package entire /www with config files that define it

recipes/valgrind/files/arm-cortex-support.patch, recipes/valgrind/valgrind.inc
The patch to make valgrind's configure system recognize arm-cortexa* was
omitted from the upgrade to 3.12, but it is still needed. Add it back in
a slightly modified form
- only patch the .ac file since we now do autoreconf anyway
- add a patch header
- put it into non-version specific subdirectory, since we're likely
going to need this forever
- only apply it when the target cpu is indeed arm
=> valgrind: re-add arm-cortex-support.patch

recipes/busybox/busybox.inc
The default configuration relies on /dev/rtc symlink, which is created
by init-devtmpfs oneshot service.  Without this fix, rtc service might
fail.
=> busybox: Fix default s6-rc dependencies for rtc service

recipes/s6-init/s6-init/klogd-log.run
They are generally just noisy, and will thus clutter your logs and fill up
your disks.
=> s6-init: Do not log kernel debug messages

recipes/busybox/files/busybox-mdev
If devtmpfs is already mounted on /dev use this instead of creating and
repopulating new tmpfs.
=> busybox-mdev: use existing devtmpfs for /dev if mounted

recipes/s6-init/s6-init.oe, recipes/s6-init/s6-init/USE_s6_init_real_sysctl/init-sysctl.up
If you are okay with including sysctl command in your filesystem, you
can just as well use it instead of the execline alternative.
=> s6-init: Add alternative init-sysctl.up script using sysctl command

recipes/pcre/pcre.inc
The libc RDEPENDS is managed directly in the DEPENDS_${PN}-lib*
assignments, the removed line was unneeded.
The AUTO_PACKAGE_LIBS_DEV_RDEPENDS assignment ensures that the pcre-dev
package gets installed when fx. target:libpcre-dev is added to RDEPENDS
in an sdk-image recipe.
The FILES_* assignments places the header files in the corresponding
library specific -dev package.
=> pcre: Fixup library packaging

recipes/stress-ng/files/0002-Add-autodetection-for-64-byte-alignment-of-functions.patch, recipes/stress-ng/files/0003-Makefile-add-missing-.PHONY-and-correct-spelling-of-.patch, recipes/stress-ng/files/0004-Fix-test-for-64K-alignment-instead-of-64-byte.patch, recipes/stress-ng/stress-ng.inc, recipes/stress-ng/stress-ng_0.07.27.oe, recipes/stress-ng/stress-ng_0.07.27.oe.sig
There's a build problem on ARM with binutils < 2.26 (on my host which
has 2.26, I cannot reproduce it, but current meta/core is at 2.25). The
included patches are from upstream, so shouldn't be needed in the next
release.
=> stress-ng: new recipe

recipes/busybox/busybox-configure.inc
The shell already provides the getopts builtin, but that only supports
short options. About the only reason one would want to enable the
getopt utility is to support long option parsing, so let the
busybox_getopt use flag also enable FEATURE_GETOPT_LONG instead of
making that a separate use flag.
=> busybox: add use flag for getopt utility

recipes/curl/curl.inc
Kept disabled by default, for backwards compatibility.
=> curl: Add USE_curl_smtp flag for SMTP support

recipes/openssl/openssl-1.0.2/parallel-symlinking.patch, recipes/openssl/openssl_1.0.2j.oe
From
<https://gitweb.gentoo.org/repo/gentoo.git/plain/dev-libs/openssl/files/openssl-1.0.2a-parallel-symlinking.patch>.
A slightly cleaner (IMO) alternative to #529.
=> openssl: fix symlink creation race

recipes/jq/jq.inc
When the host's bison is < 3.0, do_configure complains
configure: error: You need bison version 3.0 or greater, or use --disable-maintainer-mode.
Add a knob to add that configuration option.
=> jq: add use flag for setting --disable-maintainer-mode

recipes/openvpn/files/openvpn-log.run, recipes/openvpn/files/openvpn.hook, recipes/openvpn/files/openvpn.run, recipes/openvpn/openvpn.inc
Use the rc.hooks mechanism to create one openvpn service for each
configuration file found in /etc/openvpn/. For now, let them all use the
same logger; that should be easy enough to change if required.
I've tested that the services are created as expected for each .conf
file, but I don't have an example .conf to test whether the service
actually works (I do get complaints in the log about an incomplete
configuration, though, so the logging seems to work).
=> openvpn: add s6 init support

recipes/dhcp/dhcp-4.3.5/disable-syslog.patch, recipes/dhcp/dhcp4.inc, recipes/dhcp/dhcp_4.3.5.oe, recipes/dhcp/files/dhcpd-log.run, recipes/dhcp/files/dhcpd.run
--no-pid is self-explanatory
-f means don't fork
-d means log to stderr (which actually implies -f, but it's better to be
explicit).
Unfortunately, there's no option to make dhcpd not use syslog(3), so
that would require patching dhcpd. Alternatively, one can decide that
e.g. LOG_LOCAL7 (and making sure to set 'log-facility local7' in
dhcpd.conf) messages should be filtered away by one's syslogd
replacement, so that they at least don't take up disk space twice.
Signed-off-by: Rasmus Villemoes <rasmus.villemoes@prevas.dk>
=> dhcp: add s6 init support

recipes/vsftpd/files/vsftpd-log.run, recipes/vsftpd/files/vsftpd.run, recipes/vsftpd/vsftpd.inc
vsftpd has no way of getting it to log to stdout/stderr. Instead, we
have to tell it to write to the fifo s6-log is reading from. Setting
these on the command line means one doesn't have to deal with this in
the .conf file. It doesn't actually appear to ever write anything to
stdout/stderr, so one might want to redirect those to /dev/null, but I
suppose having them point at the fifo doesn't hurt.
Note that vsftpd reads the default configuration file (/etc/vsftpd.conf)
after parsing the command line if (and only if) no configuration files
were given on the command line.
The one logging-related thing one might do in the .conf file is to set
xferlog_std_format=YES if one wants wu-ftpd compatible logs (whatever
that means).
=> vsftpd: add s6 init support

recipes/overlay-files/files/overlay.sh
If /etc/openvpn already exists as a symlink to
/etc/openvpn.default, doing
ln -sf /some/where /etc/openvpn
ends up creating the link where inside /etc/openvpn.default, rather than
making /etc/openvpn itself a symlink to /some/where. Add -n to avoid
dereferencing the target.
If /etc/openvpn is itself a directory, this will still end up creating
the symlink inside that directory, but this at least fixes the common
case where the symlink openvpn->openvpn.default has been created by
do_rstage_overlay_files.
=> overlay-files: allow symlinking to a directory

recipes/ntp/files/ntp.conf, recipes/ntp/files/ntpd, recipes/ntp/ntpstat/0001-ntpstat-0.2-clksrc.patch, recipes/ntp/ntpstat/0002-ntpstat-0.2-multipacket.patch, recipes/ntp/ntpstat/0003-ntpstat-0.2-sysvars.patch, recipes/ntp/ntpstat/0004-ntpstat-0.2-maxerror.patch, recipes/ntp/ntpstat/0005-ntpstat-0.2-errorbit.patch, recipes/ntp/ntpstat/0006-ntpstat-0.2-manual.patch, recipes/ntp/ntpstat/ntp_is_synced, recipes/ntp/ntpstat_0.2.oe, recipes/ntp/ntpstat_0.2.oe.sig
This fixes a few bugs in the default ntp.conf as well as the sysvinit script, and adds simple utilities that can be used to query ntpd for how accurate the system clock is.
=> ntp tweaks

recipes/s6-init/s6-init/service
The s6-rc state machine will be blocked while the `s6-rc change` command is
running.  Without a timeout, we could thus block forever.
See https://www.mail-archive.com/supervision@list.skarnet.org/msg01683.html
And as reboot is handled as an s6-rc state machine transition, we will not
even be able to reboot in those cases.
This change introduces a hard-coded 10 second timeout service start and stop
commands.  If the timeout fires, any changes happening later will be picked up
by s6-rc on next `s6-rc change` call.
=> s6-init: Add timeout to avoid s6-rc state machine block

recipes/ntp/files/ntp.conf, recipes/s6-init/s6-init/rtc.down, recipes/util-linux/util-linux-2.29/hwclock-localtime.patch, recipes/util-linux/util-linux-2.29/hwclock-tweak-delay.patch, recipes/util-linux/util-linux_2.29.oe
This fixes a stupid bug in ntp.conf I introduced while trying to fix another, and patches hwclock to allow preserving synchronized time to almost centisecond precision on some non-x86 platforms.
=> more ntp/rtc fixes

recipes/openvpn/files/openvpn.hook
In addition to creating the openvpn@X services for each X.conf, also
create a bundle simply called openvpn that contains all of these
services.
The lack of -p in the mkdir command is deliberate; this ensures that
we're actually creating a new bundle and do not clobber some other
hook's output (the caller of the hook script is supposed to have created
the ${1} directory). We still need to create an empty contents file
explicitly in case there are no .conf files.
=> openvpn: create bundle consisting of all openvpn@* services

recipes/util-linux/util-linux_2.29.oe
While the patch added in f485a62 made it possible to avoid losing
precision when doing hwclock --systohc, in practice it turns out to be
cumbersome to ensure that every call in an entire BSP passes the
appropriate --delay option.
So allow setting USE_hwclock_delay in e.g. a machine configuration. This
could probably replace the patch added in f485a62 (i.e., simply change
the hard-coded default, without adding a command-line switch to override
it), but partly because that's already merged, partly because there
might be hardware out there with two different RTCs that need different
--delay args, I'm just adding this on top.
=> util-linux: allow compile-time changing of default --delay option

recipes/s6-init/s6-init.oe
The `-F` flag should ofcourse not be dropped.
=> s6-init: Fix use of USE_system_watchdog_device

recipes/s6-init/s6-init/syslogd-srv.filter
The current sed script ends up buffering its output, so that lines
arrive at the s6-log instance in batches, which means that the time
stamps they get have little to do with when the lines were produced, and
moreover there's obviously a greater chance of losing messages that way.
Prepending stdbuf -oL turns out to only partially solve the
problem. While busybox sed does happen to use libc's stdio, a quirk of
its implementation means that it reads line n+1 before processing (and
hence printing) line n, so there would be a delay of one line - and all
lines would be timestamped with a stamp that really belongs to the
following line.
This awk script seems to be equivalent, works with both busybox and
GNU awk, and explicitly flushes stdout after every print.
=> s6-init: prevent the syslogd filter script from buffering log lines

classes/s6rc-sanity.oeclass, recipes/skaware/execline.inc, recipes/skaware/s6-rc.inc, recipes/skaware/s6.inc, recipes/skaware/skalibs.inc
These three patches allow one to do a build-time check for cyclic dependencies and other errors in the s6 services by inheriting s6rc-sanity from one's rootfs recipe.
=> s6-rc sanity checking

recipes/ntp/files/ntpd.run
Currently, the ntpd s6 service logs to both syslog and stderr. Reading
the source code, it turns out that giving "stdout" or "stderr" as
arguments to the logfile configuration directive (equivalently, the -l
option) are special cased to DTRT, and the presence of the -l option has
the side effect of suppressing syslog output.
It is most sensible to hardcode this option in the .run script rather
than relying on it being part of NTPD_START_ARGS_PLACEHOLDER, since
the script is already setting up stdout/stderr to point at the ntpd-log
companion service.
=> ntpd: avoid logging to syslog

recipes/s6-init/s6-init/init.stage1, recipes/skaware/skalibs.inc
This aligns default path with default (root) path in busybox, which is
/sbin:/usr/sbin:/bin:/usr/bin
=> skalibs: Fix default path

recipes/dhcp/dhcp-4.3.5/0001-site.h-enable-gentle-shutdown.patch, recipes/dhcp/dhcp_4.3.5.oe
Currently, dhcpd doesn't react to either SIGINT or SIGTERM. It has
handlers installed for these, and gdb says that they actually get called
and set the flag they're supposed to. But something in the event loop is
broken, so that flag is somehow not honoured.
Those signal handlers are actually installed in code linked in from
bind (lib/isc/unix/app.c), depending on a maze of ifdefs. On
Debian/Ubuntu, it turns out that isc__app_ctxstart gets monkey-patched
to return early just before any of the signal-handling business starts,
so dhcpd simply has the default action for SIGTERM.
Yocto solves this in another way, which is what we copy here. It turns out
that by setting ENABLE_GENTLE_SHUTDOWN in site.h, dhcpd itself installs
another handler for these, and that happens after the libbind init …
=> dhcp: enable 'gentle shutdown'

recipes/netbase/netbase.inc
Add dependency on init-sysctl service, as can potentially be used for
configuring various network settings (fx. enable/disable of ipv6).
This is already done for net-auto service
=> netbase: Add init-sysctl dependency to ifplugd s6-rc service

recipes/jansson/jansson.inc, recipes/libnl/libnl.inc
A certain project I'm working on uses jansson and libnl, and it's nice to be able to compile it for native as well as the target. native:jansson passes packageqa; native:libnl builds but does not pass packageqa, but neither does its machine: cousin currently.
=> enable some recipes for native

recipes/netbase/netbase/ifplugd.run
We're already setting up stdout/stderr to go to the network-log service,
there's no point in having ifplugd write the same info to syslog. So
just as it makes sense to hardcode the -n (don't "daemonize") in the s6
run script, also hardcode -s (don't syslog), regardless of what $ARGS
happen to contain.
=> netbase: avoid ifplugd writing to syslog

recipes/netbase/netbase.inc
The net-rename service only exists in an out-of-tree layer, so should
not be included here.
=> netbase: Fix s6-rc dependency on out-of-tree service

recipes/openssh/files/openssh-log.run, recipes/openssh/openssh.inc
For non-obvious reasons, openssh ends all its stderr output with
"\r\n". We could try to patch that out, but I'm a little worried that
there's a reason openssh does it the way it does (maybe that code path
is sometimes used for something that goes over the wire and CRLF is
explicitly mentioned in the ssh spec). Instead, just make sure that what
hits s6-log doesn't contain CR.
One might argue that dos2unix would be a more appropriate filter, but at
least busybox dos2unix does exactly the same thing as tr -d '\r' (i.e.,
it removes all CR and not just those immediately preceding a LF).
Aside: in my first attempt, I used single-quotes, but execline doesn't
grok those, so tr got invoked with the three-character string
<squote><r><squote>, giving amusing log lines such as
openssh: Seve …
=> openssh: remove \r from log output

recipes/openresolv/openresolv.inc, recipes/openresolv/openresolv_3.9.0.oe, recipes/openresolv/openresolv_3.9.0.oe.sig
We amend the included resolvconf.conf by disabling all hooks except
libc, since most embedded systems probably don't have the software in
question anyway, and for the libc hook we avoid doing a lot of work to
figure out how to restart a probably-not-even-existing nscd service.
The user of this recipe may of course provide his own openresolv-config
overriding all of that.
=> openresolv: new recipe

recipes/dhcp/files/dhcpd.run, recipes/netbase/netbase/ifplugd.run, recipes/netbase/netbase/net-hotplug.hook, recipes/netbase/netbase/net-udhcpc.hook, recipes/netbase/netbase/udhcpc.run, recipes/openssh/files/openssh-keygen.up, recipes/openvpn/files/openvpn.hook, recipes/openvpn/files/openvpn.run, recipes/s6-init/s6-init/hostname.up, recipes/s6-init/s6-init/init-sysctl.up, recipes/s6-init/s6-init/mount-cgroups.up, recipes/s6-init/s6-init/rtc.down, recipes/s6-init/s6-init/rtc.up, recipes/s6-init/s6-init/s6-init-compile
After the update of execline, many scripts spit out 'import: warning: the import command and directive are obsolescent, please use importas instead!'. Fix them up to use importas.
These are scripted, so please review. The github gui may do a decent job of highlighting the relevant parts of the lines, but another good way to see the changes are with
```
git diff --word-diff=color --word-diff-regex='.' master..
```
=> update various execline scripts

recipes/netbase/netbase.inc
Allow override of /etc/protocols /etc/services and /etc/rpc on individual
bases.
Also, move all init related files to netbase-init package, allowing
whole-sale replacement of that, while keeping the rest of netbase.
This is for all reasonable uses backwards compatible.
=> netbase: Split up into more packages

recipes/openssh/openssh.inc
By default, openssh set a PATH of /usr/bin:/bin:/usr/sbin:/sbin for a
new session. This is different from the default busybox value of
/sbin:/usr/sbin:/bin:/usr/bin .
The value used by openssh can be set at configure time with the
--with-default-path option, and if a different value is required for
uid 0, --with-superuser-path. We can easily allow e.g. the distro to
set these values by providing USE flags for them, the absence of which
will just keep the current behaviour.
=> openssh: allow default ssh session PATH to be set via USE flags

recipes/lttng/lttng-modules/0001-Fix-update-timer-instrumentation-on-4.16-and-4.14-rt.patch, recipes/lttng/lttng-modules_2.10.4.oe
We can drop this patch when 2.10.6 comes out, but for now I need this.
=> lttng-modules: fix compilation against 4.14-rt kernels

classes/s6rc-sanity.oeclass
In order to allow statically defined services (i.e. in /etc/rc) to have a
producer-for/consumer-for relation to a dynamic service (i.e. one created by a
hook in /etc/rc.hooks/), we create dummy longrun services instead of empty
bundles, and take care to add needed producer-for/consumer-for relations.
Hopefully the hooks will also do the right thing.
=> class/s6rc-sanity: Fix pipeline dependencies on dynamic services

recipes/s6-init/s6-init/service
Adding a '-b' option to service command allows blocking on the s6-rc lock
starting and stopping services.  Without this, service command fails when
called while another (s6-rc) program holds the lock, spewing error messages
like
s6-rc: fatal: unable to take locks: Resource temporarily unavailable
This is generally the safe approach, so it is kept as the default.
But when using service command while changing s6-rc state (for example during
boot), it can be convenient to wait for the s6-rc lock to be released.
A valid use-case is when an application (that is not running as an s6-rc
service!) wants to stop an s6-rc service.  To avoid failure when started
during boot, the -b option is very helpful.
Note: The -b option must not be used in nested s6-rc invocation.  Anything
running with the the …
=> s6-init: Allow blocking mode to service command

recipes/lttng/lttng-ust.inc
Ensure that lttng-ust-dev is included when lttng-ust provided libraries
are included in sdk (RDEPENDS).
=> lttng-ust: Fix missing header files in SDK

recipes/openssl/openssl.inc
* Move the library specific .pc files in the corresponding library -dev
packages.
* Ensure that openssl-dev is pulled in by library -dev packages, as it
contains all the header files.
=> openssl: Minor fixups

recipes/fastcgi/fastcgi.inc
Include the header files directly in the fastcgi-libfcgi-dev package,
so they are always included in SDK together with libfcgi.
=> fastcgi: Fix library header packaging

recipes/lmsensors/lmsensors.inc
Include the header files directly in the lmsensors-libsensors-dev package,
so they are always included in SDK together with libsensors.
=> lmsensors: Fix library header packaging

recipes/lftp/lftp.inc, recipes/splashutils/splashutils.inc
Otherwise, default MIRRORS settings are overwritten, causing problems if/when upstream mirrors stop
hosting the files.
=> Mirrors append

recipes/ppp/files/in-h-header-sync.patch, recipes/ppp/ppp.inc
Backport from https://github.com/paulusmack/ppp, which seems to be the current upstream.
But no releases since 2014 (2.4.7), so maybe we should start building from master branch
instead.
=> ppp: Backport fix for build problem with newish linux-headers

recipes/net-tools/files/net-tools-fix-building-with-linux-4.8.patch, recipes/net-tools/net-tools_1.60.oe
Allows building net-tools with linux-headers 4.8 and newer.
=> net-tools: Backport patch from OpenEmbedded

recipes/iw/iw_3.7.oe
This patch was dropped when 3.15 was added (commit
cf3646b080f213f958509cdfa769ca9246c2f9ff).  It is not needed for 3.15,
but is still needed for 3.7, depending on the exact build setup.
When TMPDIR is relative to manifest, this fix avoids picking up the git
version information from the manifest.
=> iw: Fix version.sh for old iw 3.7
